### ISSUE TITLE
A binary of Mist?

### ISSUE THREAD

**Issue by Stakker** [centrevillage/cv_logue#1]
Hi! I'm sorry to bother you by making this Issue, but I'm wondering if there's a pre-built binary of Mist somewhere? It looks really interesting and I'd like to try it, but I don't know anything about the Korg SDK :-)

Thank you!

**Comment by ashenomo** [comment]
AFAIU [mist.mnlgxdunit](https://github.com/centrevillage/cv_logue/blob/master/osc/mist/mist.mnlgxdunit) is the binary. I was able to load this on an NTS1 by pointing the librarian to this file.
Unfortunately, I only got it to produce a sawtooth wave. A and B knobs don't seem to affect the sound at all.

I was also able to load the [wt_test oscillator](https://github.com/centrevillage/cv_logue/blob/master/osc/wt_test/wt_test.mnlgxdunit) in this package. The shape knob seems to adjust the wavetable position for that one.

**Comment by Stakker** [comment]
Ahh so it seems, thank you. That looks like a Monologue DX binary though, and I have a Prologue.

**Comment by Tolsi** [comment]
Oh lol, I thought something was not working, I also heard a saw, but these are just the default settings. Just hold the OSC button and turn the TYPE - so you will find the oscillator settings that you can change. I think you can close this issue. I like this sound!

**Comment by Stakker** [comment]
Ok cheers, I’ll try it :-)
